routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@index')->name('homepage');

Route::resource("menu", "MenuController");
Route::resource("product", "ProductsController");
Route::resource('user', 'UserController');
Route::resource('admin', 'AdminController');

resources/views/admin/create.blade.php
@extends("layouts.main")

@section("content")


<section id="interior">
    <div class="container-internal">
        <div class="panel panel-default">
            <legend>{{ isset($menu) ? 'Redaguoti meniu' : 'Pridėti naują meniu' }}</legend>
            <div class="panel-body">

				@if(session('messages'))
					<div class="box-body">
				        <div class="alert alert-warning alert-dismissible">
				        	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				       		<h4><i class="icon fa fa-warning"></i> Yra klaidų!</h4>
				       		<ul>
				       		@foreach(session('messages')->all() as $error)
				        		<li>{{ $error }}</li>
				        	@endforeach
				        	</ul>
				    	</div>
				    </div>
			    @endif

				@if(isset($menu))
					{{ Form::open(['route' => ['admin.update', $menu->id], 'method' => "POST"]) }}
					{{ Form::hidden('_method', 'PUT') }}
				@else
					{{ Form::open(['route' => 'admin.store', 'method' => "POST"]) }}
				@endif 

				{{ csrf_field() }}

					{{ Form::label('title', 'Pavadinimas') }}
					@if(isset($menu))
						{{ Form::text('title', ($menu['title']), ['class' => 'form-control']) }}
					@else
						{{ Form::text('title', '', ['class' => 'form-control']) }}
					@endif


				@if(isset($menu))
					{{ Form::submit('Redaguoti', ['class' => 'btn btn-primary btn-xs']) }}
				@else
					{{ Form::submit('+ Pridėti', ['class' => 'btn btn-primary btn-xs']) }}
				@endif


				{{ Form::close() }}

				@if(isset($menu))
					{{ Form::open(['route' => ['admin.destroy', $menu->id], 'method' => "POST"]) }}
					{{ Form::hidden('_method', 'DELETE') }}
							{{ csrf_field() }}
						{{ Form::submit('Trinti', ['class' => 'btn btn-danger btn-xs']) }}
					{{ Form::close() }}
				@endif

            </div>
        </div>
    </div>
</section>

@endsection

resources/views/admin/index.blade.php
@extends("layouts.main")

@section("content")

<section id="interior">
  <div class="container-internal">
    <div class="panel panel-default">
      <div class="panel-body">
        <a href="{{ route('admin.create') }}" class="btn btn-primary btn-xs pull-left"><b>+</b> Pridėti naują meniu</a>
        <table class="table table-striped custab">
          <thead>
            <tr>
              <th>ID</th>
              <th>Pavadinimas</th>
              <th>Redaguota</th>
              <th class="text-center">Veiksmas</th>
            </tr>
          </thead>
          @foreach($menus as $menu)
          <tr>
            <td>{{ $menu->id }}</td>
            <td><a href="{{ route('admin.show', $menu->id) }}">{{ $menu->title }} <i class="fa fa-angle-double-right" aria-hidden="true"></i></a></td>
            <td>{{ $menu->updated_at }}</td>
            <td class="text-center">
              <div class="col-xs-6 text-right">
              <a href="{{ route('admin.edit', $menu->id) }}" class='btn btn-info btn-xs'>
                  <span class="glyphicon glyphicon-edit"></span> 
                  Redaguoti
              </a> 
              </div>
              <div class="col-xs-6 text-left">
              {{ Form::open(['route' => ['admin.destroy', $menu->id], 'method' => "POST"]) }}
              {{ Form::hidden('_method', 'DELETE') }}
                      {{ csrf_field() }}
                  {{Form::button('<span class="glyphicon glyphicon-remove"></span> Trinti', array('type' => 'submit', 'class' => 'btn btn-danger btn-xs'))}}
              {{ Form::close() }}
              </div>
            </td>
          </tr>
          @endforeach
        </table>
      </div>
    </div>
  </div>
</section>

@endsection

resources/views/admin/show.blade.php
@extends("layouts.main")

@section("content")

<section id="interior">
  <div class="container-internal">
    <div class="panel panel-default">
      <div class="panel-body">
        <a href="{{ URL::route('product.create') }}" class="btn btn-primary btn-xs pull-left"><b>+</b> Pridėti naują gaminį</a>
        <table class="table table-striped custab">
        @if(count($products) == 0)
                   <div class="text-center col-md-12">
                     <i class="fa fa-warning"></i>
                     <p>Gaminių nėra.</p>
                   </div>
        @else
          <thead>
            <tr>
              <th></th>
              <th>Pavadinimas</th>
              <th>Kaina</th>
              <th>Aprašymas</th>
              <th class="text-center">Veiksmas</th>
            </tr>
          </thead>
          @foreach($products as $menu)
          <tr>
            <td><img src="{{ asset('img/products_photo') }}/{{ $menu->photo }}" alt="{{ $menu->photo }}" height="30"></td>
            <td>{{ $menu->title }}</td>
            <td>{{ $menu->dimensions_price }}<br>{{ $menu->price }} </td>
            <td>{!! $menu->description !!}</td>
            <td class="text-center">
              <div class="col-xs-6 text-right">
              <a href="{{ route('product.edit', $menu->id) }}" class='btn btn-info btn-xs'>
                  <span class="glyphicon glyphicon-edit"></span> 
                  Redaguoti
              </a> 
              </div>
              <div class="col-xs-6 text-left">
              {{ Form::open(['route' => ['product.destroy', $menu->id], 'method' => "POST"]) }}
              {{ Form::hidden('_method', 'DELETE') }}
                      {{ csrf_field() }}
                  {{Form::button('<span class="glyphicon glyphicon-remove"></span> Trinti', array('type' => 'submit', 'class' => 'btn btn-danger btn-xs'))}}
              {{ Form::close() }}
              </div>
            </td>
          </tr>
          @endforeach
        @endif
        </table>
      </div>
    </div>
  </div>
</section>

@endsection