routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@index')->name('homepage');

Route::resource("menu", "MenuController");
Route::resource("product", "ProductsController");
Route::resource('user', 'UserController');
Route::resource('admin', 'AdminController');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'is_admin',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use Auth;
use Validator;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (Auth::guest()) {
            return redirect("/login");
        } else {
            $user = \App\User::find($id);
            return view('user.show', compact('user'));
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/user/create.blade.php
@extends("main")

@section("content")

<h3>{{ isset($user) ? 'Edit user' : 'Add user' }}</h3>


@if(isset($errorMessages))
    <ul class="error">
        <h4>Yra klaidu</h4>
        @foreach($errorMessages->all() as $error)
            <li>
                {{ $error }}
            </li>
        @endforeach
    </ul>
@endif



@if(isset($user))
	{{ Form::open(['route' => ['user.update', $user->id], 'method' => "POST"]) }}
	{{ Form::hidden('_method', 'PUT') }}
@else
	{{ Form::open(['route' => 'user.store', 'method' => "POST"]) }}
@endif 

{{ csrf_field() }}

	{{ Form::label('name', 'Name') }}
	@if(isset($user))
		{{ Form::text('name', ($user['name']), ['class' => 'form-control']) }}
	@else
		{{ Form::text('name', '', ['class' => 'form-control']) }}
	@endif

	{{ Form::label('email', 'E-mail') }}
	@if(isset($user))
		{{ Form::text('email', ($user['email']), ['class' => 'form-control']) }}
	@else
		{{ Form::text('email', '', ['class' => 'form-control']) }}
	@endif

	@if(isset($user))
		{{ Form::label('is_admin', 'Admin?') }}
		{{ Form::hidden('is_admin', 0 ) }}
		{{ Form::checkbox('is_admin', 1, $user->is_admin) }}
	@else
	@endif

	@if(isset($user))
	@else
		{{ Form::label('password', 'Password') }}
		{{ Form::text('password', '', ['class' => 'form-control']) }}
	@endif


@if(isset($user))
	{{ Form::submit('Edit user', ['class' => 'btn btn-primary']) }}
@else
	{{ Form::submit('Add user', ['class' => 'btn btn-primary']) }}
@endif


{{ Form::close() }}

@if(isset($user))
	{{ Form::open(['route' => ['user.destroy', $user->id], 'method' => "POST"]) }}
	{{ Form::hidden('_method', 'DELETE') }}
			{{ csrf_field() }}
		{{ Form::submit('Delete', ['class' => 'btn btn-danger']) }}
	{{ Form::close() }}
@endif



@endsection

resources/views/user/show.blade.php
@extends("layouts.main")

@section("content")

<section id="interior">
    <div class="container-internal">
        <div class="margin-bottom">
            <a class="pull-left" href="#">
                <img class="media-object dp img-circle" src="{{ asset('img/user.png') }}" style="width: 100px;height:100px;">
            </a>
            <div class="media-body">
                <div class="media-heading">
                    <small>
                        @php
                            switch ($user->is_admin) {
                                case 3:
                                    echo 'Darbuotojas';
                                    break;
                                case 2:
                                    echo 'Administracija';
                                    break;
                                case 1:
                                    echo 'Vadovas';
                                    break;
                                default:
                                    echo 'Lankytojas';
                            }
                        @endphp
                    </small>
                    {{ $user->name }}
                    <div class="pull-right">
                    <a href="{{ url('/logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();" class="btn btn-xs btn-default btn-flat">
                      Atsijungti
                    </a>
                    <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                      {{ csrf_field() }}
                    </form>
                    </div>
                </div>
                <hr style="margin:8px auto">
                <span>Redaguoti:</span><br>
                <a href="{{ route('user.create') }}" class="btn btn-default btn-xs disabled">Savo profilį</a>
                <a href="{{ route('admin.index') }}" class="btn btn-primary btn-xs">meniu ir gaminius</a>
            </div>
        </div>
        <div class="panel panel-default">
            <legend>Įvertink mūsų paslaugas</legend>
            <div class="panel-body">
                Neužilgo
            </div>
        </div>
        <div class="panel panel-default">
            <legend>Palik atsiliepimą</legend>
            <div class="panel-body">
                Neužilgo
            </div>
        </div>
    </div>
</section>

@endsection